export * from "./ambientes.js";
export * from "./alunos.js";
export * from "./auth.js";
export * from "./cursos.js";
export * from "./ferramentas.js";
export * from "./novidades.js";
export * from "./trabalhos.js";
export * from "./comentarios.js";
export * from "./logs.js";
