/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AlunoRouteImport } from './routes/aluno'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlunoIndexRouteImport } from './routes/aluno.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AlunoLoginRouteImport } from './routes/aluno.login'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const AlunoRoute = AlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoIndexRoute = AlunoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlunoRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AlunoLoginRoute = AlunoLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AlunoRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aluno': typeof AlunoRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/aluno/login': typeof AlunoLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/aluno/': typeof AlunoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/aluno/login': typeof AlunoLoginRoute
  '/admin': typeof AdminIndexRoute
  '/aluno': typeof AlunoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aluno': typeof AlunoRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/aluno/login': typeof AlunoLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/aluno/': typeof AlunoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aluno'
    | '/admin/login'
    | '/aluno/login'
    | '/admin/'
    | '/aluno/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/login' | '/aluno/login' | '/admin' | '/aluno'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aluno'
    | '/admin/login'
    | '/aluno/login'
    | '/admin/'
    | '/aluno/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlunoRoute: typeof AlunoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/aluno': {
      id: '/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/': {
      id: '/aluno/'
      path: '/'
      fullPath: '/aluno/'
      preLoaderRoute: typeof AlunoIndexRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/aluno/login': {
      id: '/aluno/login'
      path: '/login'
      fullPath: '/aluno/login'
      preLoaderRoute: typeof AlunoLoginRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AlunoRouteChildren {
  AlunoLoginRoute: typeof AlunoLoginRoute
  AlunoIndexRoute: typeof AlunoIndexRoute
}

const AlunoRouteChildren: AlunoRouteChildren = {
  AlunoLoginRoute: AlunoLoginRoute,
  AlunoIndexRoute: AlunoIndexRoute,
}

const AlunoRouteWithChildren = AlunoRoute._addFileChildren(AlunoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlunoRoute: AlunoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
