/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AlunoRouteImport } from './routes/aluno'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlunoIndexRouteImport } from './routes/aluno.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AlunoLoginRouteImport } from './routes/aluno_.login'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AdminAmbientesIndexRouteImport } from './routes/admin.ambientes.index'
import { Route as AdminAmbientesNovoRouteImport } from './routes/admin.ambientes.novo'

const AlunoRoute = AlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoIndexRoute = AlunoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlunoRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AlunoLoginRoute = AlunoLoginRouteImport.update({
  id: '/aluno_/login',
  path: '/aluno/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAmbientesIndexRoute = AdminAmbientesIndexRouteImport.update({
  id: '/ambientes/',
  path: '/ambientes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAmbientesNovoRoute = AdminAmbientesNovoRouteImport.update({
  id: '/ambientes/novo',
  path: '/ambientes/novo',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aluno': typeof AlunoRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/aluno/login': typeof AlunoLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/aluno/': typeof AlunoIndexRoute
  '/admin/ambientes/novo': typeof AdminAmbientesNovoRoute
  '/admin/ambientes/': typeof AdminAmbientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/aluno/login': typeof AlunoLoginRoute
  '/admin': typeof AdminIndexRoute
  '/aluno': typeof AlunoIndexRoute
  '/admin/ambientes/novo': typeof AdminAmbientesNovoRoute
  '/admin/ambientes': typeof AdminAmbientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aluno': typeof AlunoRouteWithChildren
  '/admin_/login': typeof AdminLoginRoute
  '/aluno_/login': typeof AlunoLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/aluno/': typeof AlunoIndexRoute
  '/admin/ambientes/novo': typeof AdminAmbientesNovoRoute
  '/admin/ambientes/': typeof AdminAmbientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aluno'
    | '/admin/login'
    | '/aluno/login'
    | '/admin/'
    | '/aluno/'
    | '/admin/ambientes/novo'
    | '/admin/ambientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/aluno/login'
    | '/admin'
    | '/aluno'
    | '/admin/ambientes/novo'
    | '/admin/ambientes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aluno'
    | '/admin_/login'
    | '/aluno_/login'
    | '/admin/'
    | '/aluno/'
    | '/admin/ambientes/novo'
    | '/admin/ambientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlunoRoute: typeof AlunoRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AlunoLoginRoute: typeof AlunoLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/aluno': {
      id: '/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/': {
      id: '/aluno/'
      path: '/'
      fullPath: '/aluno/'
      preLoaderRoute: typeof AlunoIndexRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/aluno_/login': {
      id: '/aluno_/login'
      path: '/aluno/login'
      fullPath: '/aluno/login'
      preLoaderRoute: typeof AlunoLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ambientes/': {
      id: '/admin/ambientes/'
      path: '/ambientes'
      fullPath: '/admin/ambientes/'
      preLoaderRoute: typeof AdminAmbientesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ambientes/novo': {
      id: '/admin/ambientes/novo'
      path: '/ambientes/novo'
      fullPath: '/admin/ambientes/novo'
      preLoaderRoute: typeof AdminAmbientesNovoRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAmbientesNovoRoute: typeof AdminAmbientesNovoRoute
  AdminAmbientesIndexRoute: typeof AdminAmbientesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAmbientesNovoRoute: AdminAmbientesNovoRoute,
  AdminAmbientesIndexRoute: AdminAmbientesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AlunoRouteChildren {
  AlunoIndexRoute: typeof AlunoIndexRoute
}

const AlunoRouteChildren: AlunoRouteChildren = {
  AlunoIndexRoute: AlunoIndexRoute,
}

const AlunoRouteWithChildren = AlunoRoute._addFileChildren(AlunoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlunoRoute: AlunoRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AlunoLoginRoute: AlunoLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
