/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AlunoRouteImport } from './routes/aluno'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlunoIndexRouteImport } from './routes/aluno.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AlunoLoginRouteImport } from './routes/aluno_.login'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminTrabalhosRouteImport } from './routes/admin.trabalhos'
import { Route as AdminNovidadesRouteImport } from './routes/admin.novidades'
import { Route as AdminMetricasRouteImport } from './routes/admin.metricas'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminImportacoesRouteImport } from './routes/admin.importacoes'
import { Route as AdminGruposRouteImport } from './routes/admin.grupos'
import { Route as AdminFerramentasRouteImport } from './routes/admin.ferramentas'
import { Route as AdminCursosRouteImport } from './routes/admin.cursos'
import { Route as AdminComentariosRouteImport } from './routes/admin.comentarios'
import { Route as AdminAulasRouteImport } from './routes/admin.aulas'
import { Route as AdminAlunosRouteImport } from './routes/admin.alunos'
import { Route as ESlugIndexRouteImport } from './routes/e.$slug.index'
import { Route as AdminAmbientesIndexRouteImport } from './routes/admin.ambientes.index'
import { Route as ESlugResultadosRouteImport } from './routes/e.$slug.resultados'
import { Route as ESlugLoginRouteImport } from './routes/e.$slug.login'
import { Route as AdminCursosIdRouteImport } from './routes/admin.cursos.$id'
import { Route as AdminAmbientesNovoRouteImport } from './routes/admin.ambientes.novo'
import { Route as AdminAmbientesIdRouteImport } from './routes/admin.ambientes.$id'
import { Route as ESlugResultadosTrabalhoIdRouteImport } from './routes/e.$slug.resultados.$trabalhoId'
import { Route as ESlugAulaAulaIdRouteImport } from './routes/e.$slug.aula.$aulaId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoRoute = AlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoIndexRoute = AlunoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlunoRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AlunoLoginRoute = AlunoLoginRouteImport.update({
  id: '/aluno_/login',
  path: '/aluno/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrabalhosRoute = AdminTrabalhosRouteImport.update({
  id: '/trabalhos',
  path: '/trabalhos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNovidadesRoute = AdminNovidadesRouteImport.update({
  id: '/novidades',
  path: '/novidades',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMetricasRoute = AdminMetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportacoesRoute = AdminImportacoesRouteImport.update({
  id: '/importacoes',
  path: '/importacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGruposRoute = AdminGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFerramentasRoute = AdminFerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCursosRoute = AdminCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComentariosRoute = AdminComentariosRouteImport.update({
  id: '/comentarios',
  path: '/comentarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAulasRoute = AdminAulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlunosRoute = AdminAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AdminRoute,
} as any)
const ESlugIndexRoute = ESlugIndexRouteImport.update({
  id: '/e/$slug/',
  path: '/e/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAmbientesIndexRoute = AdminAmbientesIndexRouteImport.update({
  id: '/ambientes/',
  path: '/ambientes/',
  getParentRoute: () => AdminRoute,
} as any)
const ESlugResultadosRoute = ESlugResultadosRouteImport.update({
  id: '/e/$slug/resultados',
  path: '/e/$slug/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugLoginRoute = ESlugLoginRouteImport.update({
  id: '/e/$slug/login',
  path: '/e/$slug/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCursosIdRoute = AdminCursosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCursosRoute,
} as any)
const AdminAmbientesNovoRoute = AdminAmbientesNovoRouteImport.update({
  id: '/ambientes/novo',
  path: '/ambientes/novo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAmbientesIdRoute = AdminAmbientesIdRouteImport.update({
  id: '/ambientes/$id',
  path: '/ambientes/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ESlugResultadosTrabalhoIdRoute =
  ESlugResultadosTrabalhoIdRouteImport.update({
    id: '/$trabalhoId',
    path: '/$trabalhoId',
    getParentRoute: () => ESlugResultadosRoute,
  } as any)
const ESlugAulaAulaIdRoute = ESlugAulaAulaIdRouteImport.update({
  id: '/e/$slug/aula/$aulaId',
  path: '/e/$slug/aula/$aulaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aluno': typeof AlunoRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/aulas': typeof AdminAulasRoute
  '/admin/comentarios': typeof AdminComentariosRoute
  '/admin/cursos': typeof AdminCursosRouteWithChildren
  '/admin/ferramentas': typeof AdminFerramentasRoute
  '/admin/grupos': typeof AdminGruposRoute
  '/admin/importacoes': typeof AdminImportacoesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/metricas': typeof AdminMetricasRoute
  '/admin/novidades': typeof AdminNovidadesRoute
  '/admin/trabalhos': typeof AdminTrabalhosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/login': typeof AdminLoginRoute
  '/aluno/login': typeof AlunoLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/aluno/': typeof AlunoIndexRoute
  '/admin/ambientes/$id': typeof AdminAmbientesIdRoute
  '/admin/ambientes/novo': typeof AdminAmbientesNovoRoute
  '/admin/cursos/$id': typeof AdminCursosIdRoute
  '/e/$slug/login': typeof ESlugLoginRoute
  '/e/$slug/resultados': typeof ESlugResultadosRouteWithChildren
  '/admin/ambientes/': typeof AdminAmbientesIndexRoute
  '/e/$slug/': typeof ESlugIndexRoute
  '/e/$slug/aula/$aulaId': typeof ESlugAulaAulaIdRoute
  '/e/$slug/resultados/$trabalhoId': typeof ESlugResultadosTrabalhoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/aulas': typeof AdminAulasRoute
  '/admin/comentarios': typeof AdminComentariosRoute
  '/admin/cursos': typeof AdminCursosRouteWithChildren
  '/admin/ferramentas': typeof AdminFerramentasRoute
  '/admin/grupos': typeof AdminGruposRoute
  '/admin/importacoes': typeof AdminImportacoesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/metricas': typeof AdminMetricasRoute
  '/admin/novidades': typeof AdminNovidadesRoute
  '/admin/trabalhos': typeof AdminTrabalhosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/login': typeof AdminLoginRoute
  '/aluno/login': typeof AlunoLoginRoute
  '/admin': typeof AdminIndexRoute
  '/aluno': typeof AlunoIndexRoute
  '/admin/ambientes/$id': typeof AdminAmbientesIdRoute
  '/admin/ambientes/novo': typeof AdminAmbientesNovoRoute
  '/admin/cursos/$id': typeof AdminCursosIdRoute
  '/e/$slug/login': typeof ESlugLoginRoute
  '/e/$slug/resultados': typeof ESlugResultadosRouteWithChildren
  '/admin/ambientes': typeof AdminAmbientesIndexRoute
  '/e/$slug': typeof ESlugIndexRoute
  '/e/$slug/aula/$aulaId': typeof ESlugAulaAulaIdRoute
  '/e/$slug/resultados/$trabalhoId': typeof ESlugResultadosTrabalhoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aluno': typeof AlunoRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/aulas': typeof AdminAulasRoute
  '/admin/comentarios': typeof AdminComentariosRoute
  '/admin/cursos': typeof AdminCursosRouteWithChildren
  '/admin/ferramentas': typeof AdminFerramentasRoute
  '/admin/grupos': typeof AdminGruposRoute
  '/admin/importacoes': typeof AdminImportacoesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/metricas': typeof AdminMetricasRoute
  '/admin/novidades': typeof AdminNovidadesRoute
  '/admin/trabalhos': typeof AdminTrabalhosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin_/login': typeof AdminLoginRoute
  '/aluno_/login': typeof AlunoLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/aluno/': typeof AlunoIndexRoute
  '/admin/ambientes/$id': typeof AdminAmbientesIdRoute
  '/admin/ambientes/novo': typeof AdminAmbientesNovoRoute
  '/admin/cursos/$id': typeof AdminCursosIdRoute
  '/e/$slug/login': typeof ESlugLoginRoute
  '/e/$slug/resultados': typeof ESlugResultadosRouteWithChildren
  '/admin/ambientes/': typeof AdminAmbientesIndexRoute
  '/e/$slug/': typeof ESlugIndexRoute
  '/e/$slug/aula/$aulaId': typeof ESlugAulaAulaIdRoute
  '/e/$slug/resultados/$trabalhoId': typeof ESlugResultadosTrabalhoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aluno'
    | '/forgot-password'
    | '/reset-password'
    | '/admin/alunos'
    | '/admin/aulas'
    | '/admin/comentarios'
    | '/admin/cursos'
    | '/admin/ferramentas'
    | '/admin/grupos'
    | '/admin/importacoes'
    | '/admin/logs'
    | '/admin/metricas'
    | '/admin/novidades'
    | '/admin/trabalhos'
    | '/admin/usuarios'
    | '/admin/login'
    | '/aluno/login'
    | '/admin/'
    | '/aluno/'
    | '/admin/ambientes/$id'
    | '/admin/ambientes/novo'
    | '/admin/cursos/$id'
    | '/e/$slug/login'
    | '/e/$slug/resultados'
    | '/admin/ambientes/'
    | '/e/$slug/'
    | '/e/$slug/aula/$aulaId'
    | '/e/$slug/resultados/$trabalhoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/admin/alunos'
    | '/admin/aulas'
    | '/admin/comentarios'
    | '/admin/cursos'
    | '/admin/ferramentas'
    | '/admin/grupos'
    | '/admin/importacoes'
    | '/admin/logs'
    | '/admin/metricas'
    | '/admin/novidades'
    | '/admin/trabalhos'
    | '/admin/usuarios'
    | '/admin/login'
    | '/aluno/login'
    | '/admin'
    | '/aluno'
    | '/admin/ambientes/$id'
    | '/admin/ambientes/novo'
    | '/admin/cursos/$id'
    | '/e/$slug/login'
    | '/e/$slug/resultados'
    | '/admin/ambientes'
    | '/e/$slug'
    | '/e/$slug/aula/$aulaId'
    | '/e/$slug/resultados/$trabalhoId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aluno'
    | '/forgot-password'
    | '/reset-password'
    | '/admin/alunos'
    | '/admin/aulas'
    | '/admin/comentarios'
    | '/admin/cursos'
    | '/admin/ferramentas'
    | '/admin/grupos'
    | '/admin/importacoes'
    | '/admin/logs'
    | '/admin/metricas'
    | '/admin/novidades'
    | '/admin/trabalhos'
    | '/admin/usuarios'
    | '/admin_/login'
    | '/aluno_/login'
    | '/admin/'
    | '/aluno/'
    | '/admin/ambientes/$id'
    | '/admin/ambientes/novo'
    | '/admin/cursos/$id'
    | '/e/$slug/login'
    | '/e/$slug/resultados'
    | '/admin/ambientes/'
    | '/e/$slug/'
    | '/e/$slug/aula/$aulaId'
    | '/e/$slug/resultados/$trabalhoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlunoRoute: typeof AlunoRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AlunoLoginRoute: typeof AlunoLoginRoute
  ESlugLoginRoute: typeof ESlugLoginRoute
  ESlugResultadosRoute: typeof ESlugResultadosRouteWithChildren
  ESlugIndexRoute: typeof ESlugIndexRoute
  ESlugAulaAulaIdRoute: typeof ESlugAulaAulaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno': {
      id: '/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/': {
      id: '/aluno/'
      path: '/'
      fullPath: '/aluno/'
      preLoaderRoute: typeof AlunoIndexRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/aluno_/login': {
      id: '/aluno_/login'
      path: '/aluno/login'
      fullPath: '/aluno/login'
      preLoaderRoute: typeof AlunoLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trabalhos': {
      id: '/admin/trabalhos'
      path: '/trabalhos'
      fullPath: '/admin/trabalhos'
      preLoaderRoute: typeof AdminTrabalhosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/novidades': {
      id: '/admin/novidades'
      path: '/novidades'
      fullPath: '/admin/novidades'
      preLoaderRoute: typeof AdminNovidadesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/metricas': {
      id: '/admin/metricas'
      path: '/metricas'
      fullPath: '/admin/metricas'
      preLoaderRoute: typeof AdminMetricasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/importacoes': {
      id: '/admin/importacoes'
      path: '/importacoes'
      fullPath: '/admin/importacoes'
      preLoaderRoute: typeof AdminImportacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/grupos': {
      id: '/admin/grupos'
      path: '/grupos'
      fullPath: '/admin/grupos'
      preLoaderRoute: typeof AdminGruposRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ferramentas': {
      id: '/admin/ferramentas'
      path: '/ferramentas'
      fullPath: '/admin/ferramentas'
      preLoaderRoute: typeof AdminFerramentasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cursos': {
      id: '/admin/cursos'
      path: '/cursos'
      fullPath: '/admin/cursos'
      preLoaderRoute: typeof AdminCursosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comentarios': {
      id: '/admin/comentarios'
      path: '/comentarios'
      fullPath: '/admin/comentarios'
      preLoaderRoute: typeof AdminComentariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/aulas': {
      id: '/admin/aulas'
      path: '/aulas'
      fullPath: '/admin/aulas'
      preLoaderRoute: typeof AdminAulasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alunos': {
      id: '/admin/alunos'
      path: '/alunos'
      fullPath: '/admin/alunos'
      preLoaderRoute: typeof AdminAlunosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/e/$slug/': {
      id: '/e/$slug/'
      path: '/e/$slug'
      fullPath: '/e/$slug/'
      preLoaderRoute: typeof ESlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ambientes/': {
      id: '/admin/ambientes/'
      path: '/ambientes'
      fullPath: '/admin/ambientes/'
      preLoaderRoute: typeof AdminAmbientesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/e/$slug/resultados': {
      id: '/e/$slug/resultados'
      path: '/e/$slug/resultados'
      fullPath: '/e/$slug/resultados'
      preLoaderRoute: typeof ESlugResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug/login': {
      id: '/e/$slug/login'
      path: '/e/$slug/login'
      fullPath: '/e/$slug/login'
      preLoaderRoute: typeof ESlugLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cursos/$id': {
      id: '/admin/cursos/$id'
      path: '/$id'
      fullPath: '/admin/cursos/$id'
      preLoaderRoute: typeof AdminCursosIdRouteImport
      parentRoute: typeof AdminCursosRoute
    }
    '/admin/ambientes/novo': {
      id: '/admin/ambientes/novo'
      path: '/ambientes/novo'
      fullPath: '/admin/ambientes/novo'
      preLoaderRoute: typeof AdminAmbientesNovoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ambientes/$id': {
      id: '/admin/ambientes/$id'
      path: '/ambientes/$id'
      fullPath: '/admin/ambientes/$id'
      preLoaderRoute: typeof AdminAmbientesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/e/$slug/resultados/$trabalhoId': {
      id: '/e/$slug/resultados/$trabalhoId'
      path: '/$trabalhoId'
      fullPath: '/e/$slug/resultados/$trabalhoId'
      preLoaderRoute: typeof ESlugResultadosTrabalhoIdRouteImport
      parentRoute: typeof ESlugResultadosRoute
    }
    '/e/$slug/aula/$aulaId': {
      id: '/e/$slug/aula/$aulaId'
      path: '/e/$slug/aula/$aulaId'
      fullPath: '/e/$slug/aula/$aulaId'
      preLoaderRoute: typeof ESlugAulaAulaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminCursosRouteChildren {
  AdminCursosIdRoute: typeof AdminCursosIdRoute
}

const AdminCursosRouteChildren: AdminCursosRouteChildren = {
  AdminCursosIdRoute: AdminCursosIdRoute,
}

const AdminCursosRouteWithChildren = AdminCursosRoute._addFileChildren(
  AdminCursosRouteChildren,
)

interface AdminRouteChildren {
  AdminAlunosRoute: typeof AdminAlunosRoute
  AdminAulasRoute: typeof AdminAulasRoute
  AdminComentariosRoute: typeof AdminComentariosRoute
  AdminCursosRoute: typeof AdminCursosRouteWithChildren
  AdminFerramentasRoute: typeof AdminFerramentasRoute
  AdminGruposRoute: typeof AdminGruposRoute
  AdminImportacoesRoute: typeof AdminImportacoesRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMetricasRoute: typeof AdminMetricasRoute
  AdminNovidadesRoute: typeof AdminNovidadesRoute
  AdminTrabalhosRoute: typeof AdminTrabalhosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAmbientesIdRoute: typeof AdminAmbientesIdRoute
  AdminAmbientesNovoRoute: typeof AdminAmbientesNovoRoute
  AdminAmbientesIndexRoute: typeof AdminAmbientesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlunosRoute: AdminAlunosRoute,
  AdminAulasRoute: AdminAulasRoute,
  AdminComentariosRoute: AdminComentariosRoute,
  AdminCursosRoute: AdminCursosRouteWithChildren,
  AdminFerramentasRoute: AdminFerramentasRoute,
  AdminGruposRoute: AdminGruposRoute,
  AdminImportacoesRoute: AdminImportacoesRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMetricasRoute: AdminMetricasRoute,
  AdminNovidadesRoute: AdminNovidadesRoute,
  AdminTrabalhosRoute: AdminTrabalhosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAmbientesIdRoute: AdminAmbientesIdRoute,
  AdminAmbientesNovoRoute: AdminAmbientesNovoRoute,
  AdminAmbientesIndexRoute: AdminAmbientesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AlunoRouteChildren {
  AlunoIndexRoute: typeof AlunoIndexRoute
}

const AlunoRouteChildren: AlunoRouteChildren = {
  AlunoIndexRoute: AlunoIndexRoute,
}

const AlunoRouteWithChildren = AlunoRoute._addFileChildren(AlunoRouteChildren)

interface ESlugResultadosRouteChildren {
  ESlugResultadosTrabalhoIdRoute: typeof ESlugResultadosTrabalhoIdRoute
}

const ESlugResultadosRouteChildren: ESlugResultadosRouteChildren = {
  ESlugResultadosTrabalhoIdRoute: ESlugResultadosTrabalhoIdRoute,
}

const ESlugResultadosRouteWithChildren = ESlugResultadosRoute._addFileChildren(
  ESlugResultadosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlunoRoute: AlunoRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  AlunoLoginRoute: AlunoLoginRoute,
  ESlugLoginRoute: ESlugLoginRoute,
  ESlugResultadosRoute: ESlugResultadosRouteWithChildren,
  ESlugIndexRoute: ESlugIndexRoute,
  ESlugAulaAulaIdRoute: ESlugAulaAulaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
